[project]
name = "rabbit-consumer"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pika>=1.3.2",
    "pyyaml>=6.0.2",
]

[tool.uv]
dev-dependencies = [
    "pika-stubs>=0.1.3",
]
